### ISSUE TITLE
Feature: Support distro packages

### ISSUE THREAD

**Issue by rmoriz** [sous-chefs/ossec#44]
OSSEC started to provide packages for various distros (RHEL, CentOS, Debian, Ubuntu):
http://www.ossec.net/?page_id=19

Those packages provide things like init-scripts/systemd units which currently are not provided by this cookbook (except for Arch). 

It would be nice to support installation/configuration of those packages with this cookbook.

related: #43 #38

**Comment by jtimberman** [comment]
Oh nice! 

In my opinion we should just rip out all the source compile stuff and support only package installs. That's the only really sane way to maintain this going forward so we don't have all the "bump version" pull requests.

**Comment by ranjib** [comment]
:+1:

**Comment by chewi** [comment]
I've made a start on this but it's a little more painful than it should be. I don't want to add the whole "atomic" repository so I'm looking at the standalone "ossec" repository. EPEL is required for inotify-tools but that's okay. The repository lacks the 2.8.2 release and the WUI package though. The RPMs are also signed with a key that doesn't match any of the published ones. Someone else reported this almost a year ago and no one replied. Haven't looked at the DEBs yet.

**Comment by chewi** [comment]
DEBs for 2.8.2 are now up but still no WUI.

I've done a lot more on this now and have put the result so far up on our [packages branch](https://github.com/yakara-ltd/ossec-cookbook/tree/packages). I've had to break the recipes up slightly because Debian has no common package whereas CentOS does. We need to install the package in order to create the user that will own the configuration file.

Facing more issues with the DEBs including `ossec-batch-manager.pl` not being present and the ossec user being created with a home at `/home/ossec` instead of `/var/ossec`. Please follow along with the fun on the mailing list!

**Comment by tas50** [comment]
We're using packages on both RHEL and Debian now
